### ISSUE TITLE
Repository Privata

### ISSUE THREAD

**Issue by LorenzoBonetti** [Luca8991/ROSproject#1]
Le conviene impostare la repository privata

**Comment by ilbertt** [comment]
Ok!

**Comment by ilbertt** [comment]
Uso GitKraken (versione gratuita) come GUI ma questo non mi consente di lavorare con repo private. E' un problema lasciare la repo pubblica?

**Comment by LorenzoBonetti** [comment]
Non è un problema per me, le consiglio la repository privata per evitare che qualcuno trovi il suo codice e lo copi.
Potrebbe utilizzare il terminale per le operazioni.
Rimango a disposizione per ulteriori chiarimenti.
Cordialità
Lorenzo Bonetti
________________________________

**Comment by ilbertt** [comment]
Ok grazie mille!
